language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
branches:
  only:
    - release
script:
  - bundle exec jekyll build --destination site
  - grep johnotander/pixyll _site/index.html
  - grep post-title         _site/index.html
  - grep pagination-item    _site/index.html
  - grep johnotander/pixyll _site/css/pixyll.css
  - grep 404                _site/404.html
deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release
